spring.application.name=widget-api-service
server.port=8086

# Logging
logging.level.root=INFO
logging.level.com.nsind=DEBUG

# OpenAPI/Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Widget Configuration
widget.api-url=${WIDGET_API_URL:http://localhost:8086/api/v1/widget}

# Eureka Discovery
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.value}

