package com.nsind.ns.Constant;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

public class panchayatToBlockMap {

 private static final LinkedHashMap<String, String> panchayatToBlockMap = new LinkedHashMap<>();
 static {

     // ===== BUNGTE CHIRU TD BLOCK =====
     panchayatToBlockMap.put("Bungte Chiru", "BUNGTE CHIRU TD BLOCK");
     panchayatToBlockMap.put("Bungte khullen", "BUNGTE CHIRU TD BLOCK");
     panchayatToBlockMap.put("Chini Ingkhol", "BUNGTE CHIRU TD BLOCK");
     panchayatToBlockMap.put("Ichum Keirap", "BUNGTE CHIRU TD BLOCK");
     panchayatToBlockMap.put("Joupi", "BUNGTE CHIRU TD BLOCK");
     panchayatToBlockMap.put("Khoirok", "BUNGTE CHIRU TD BLOCK");
     panchayatToBlockMap.put("Khoripok", "BUNGTE CHIRU TD BLOCK");
     panchayatToBlockMap.put("Laimaton Thangbuh", "BUNGTE CHIRU TD BLOCK");
     panchayatToBlockMap.put("Loibol Khullen", "BUNGTE CHIRU TD BLOCK");
     panchayatToBlockMap.put("Loibol Khunou", "BUNGTE CHIRU TD BLOCK");
     panchayatToBlockMap.put("Manamjang", "BUNGTE CHIRU TD BLOCK");
     panchayatToBlockMap.put("Mongbung Tongneh", "BUNGTE CHIRU TD BLOCK");
     panchayatToBlockMap.put("Nunggang(Chongphun)", "BUNGTE CHIRU TD BLOCK");
     panchayatToBlockMap.put("Nungsai Chiru", "BUNGTE CHIRU TD BLOCK");
     panchayatToBlockMap.put("Parengba", "BUNGTE CHIRU TD BLOCK");
     panchayatToBlockMap.put("Sadar Joute", "BUNGTE CHIRU TD BLOCK");
     panchayatToBlockMap.put("Sadu chiru", "BUNGTE CHIRU TD BLOCK");
     panchayatToBlockMap.put("Saingai Namdai", "BUNGTE CHIRU TD BLOCK");
     panchayatToBlockMap.put("Tingkai Khullen", "BUNGTE CHIRU TD BLOCK");
     panchayatToBlockMap.put("Tingkai Khunou", "BUNGTE CHIRU TD BLOCK");
     panchayatToBlockMap.put("Tuikhang Aimol", "BUNGTE CHIRU TD BLOCK");
     panchayatToBlockMap.put("Wainem", "BUNGTE CHIRU TD BLOCK");
     panchayatToBlockMap.put("Wajang Mangkhosom", "BUNGTE CHIRU TD BLOCK");
     panchayatToBlockMap.put("Waroiching", "BUNGTE CHIRU TD BLOCK");

     // ===== CHAMPAI TD BLOCK =====
     panchayatToBlockMap.put("Bolsang", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("Bongmoul", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("C.Lamjang", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("Canaanphai", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("Chandmari", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("Gamnomphai", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("Gopibung", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("Haipi", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("J Munnom", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("Janglenphai", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("Jangmol", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("Jangnom", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("K Gamnom", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("K. Sajal", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("K.Moljol", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("K.Songtun", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("Keithelmanbi", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("Kholjang", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("Khonom", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("laloi", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("Leisanphung", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("Lhangnomphai", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("Molsang", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("N.Gamhoi", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("N.Phungchoijang", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("Natheljang", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("P Moljang", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("P.Khothah", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("Phailen", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("Phaimol", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("Phoibung", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("S Jalenmoul", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("S Khomunnom", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("S Molnom", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("S.M.Gilgal", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("Saikotjang", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("Saipimol Holjang", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("Santalbari", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("Santolbari", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("T.Lhanghoi", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("Thanamba", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("Tokpa Naga", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("Tujang Part-I", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("Tujang Part-II", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("Washangphung", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("West Selsi", "CHAMPAI TD BLOCK");
     panchayatToBlockMap.put("West Tuipajang", "CHAMPAI TD BLOCK");

     // ===== ISLAND TD BLOCK =====
     panchayatToBlockMap.put("B.Phainom", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Bethelphai", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Bewlahland", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Bongbal Khullen", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("C.Moljol", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Chaningpokpi", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Gotangkot", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Haokhongching", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Happy Land", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Heirokland", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Irong Ngoupikhong", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Irong Tangkhul", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Island Tangkhul", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("K.Heichanglok", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("K.Hengjang", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("K.Nungmanbi", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Kamu Koireng", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Kamu Leirok", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Kamu Maring", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Kamu Tampak", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Kamu Tangnom", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Kamu Themdoi", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Kamuching", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Kamusaichang", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Kaprang", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Karpur Sungba", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Keihao Tangkhul", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Keirouchingdong", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Kharan Tangkhul", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Komlaching", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Kwarok Maring", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("L.Molnom", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Laikoiching", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Laipharok Maring", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Lairok Vaiphei", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Leingangpokpi", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Leishiphung", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Lemba Khul", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Lishamlok Tkl", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Maphou Kuki", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Moirangpal", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Molkonbung", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Monglham", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("N.Heikon", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("N.Khallong", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("N.Mollen", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("N.Terakhong", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("New Salem", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Ngaranphung", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Ngarumphung", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Ngoupikhong", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Nongmaiching Tampak", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Nongmaipal", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Nongpok Centre", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Nungkot Khuman", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Nungkot Kom", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Phailengjang", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Phainom", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Pheitaiching", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Phouwaibi", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Phunal Maring", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Phungton", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Poirou Tangkhul", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Risophung", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("S Alimphai", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("S.Buongjang", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("S.Kanan", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Sada Lungthar", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Saichang", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Sailent ( T )", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Salam Patong", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Samaching", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Saman Tangkhul", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Sandang Senba Kabui", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Sangdangsenba Maring", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Selhao Vaiphei", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Somrei", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Songphel", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Soraland (T)", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("South Loushing", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Tangkhul Khullen", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Teraphai", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Th.Salemphai", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Thangja", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Thangjingpokpi", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Thayong", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Tombi hangbu", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Tongko Tangkhul", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Tuisenphai", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Uran Chiru", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Vaiphei pakai", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Waithou Chiru", "ISLAND TD BLOCK");
     panchayatToBlockMap.put("Zeru Canan", "ISLAND TD BLOCK");

     // ===== KANGCHUP GELJANG TD BLOCK =====
     panchayatToBlockMap.put("Bethel", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Bijang", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Ch.Ebenezer", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Haibung", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Haraothel", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Irang Naga", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("K Songlung", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("K.Khomunnom", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("K.Patbung", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("K.Phaijol", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("K.Ponlen", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Kangchup Chingkhong", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Kangchup Chiru", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Kangchup Geljang", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Kangchup Khul Bangla", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Kangchup Makhom", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Kangchup Patjang", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Kangchup Tuikun", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Kharam Pallen", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Kharam Thadoi", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Kharam Vaiphei", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Khoken", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Khonglong Kabui", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Khonglong Part (II)", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Konsakhul", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Kotlen", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("L. Hengjang", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("L.Champhai", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("L.Hengjol", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("L.Jangnoumphai", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("L.Munlui", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("L.Phaijang", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("L.Phaikot", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Langdeibung", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("lanthunching1", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Leilon Khunou", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Leilon Vaiphei", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Leimakhong", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Leimakhong Mission Veng", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Lhongchin", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Longa Koireng", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Lonjang", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Machangram", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Maha Kabui", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Molhoi", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("N Boljang", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("N.C.Phai", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Nakhojang", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Namthanjang", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Natop Kabui", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("New Keithelmanbi", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("P.Molding", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Pholjang", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Pongringlong", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Ramgailong", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("S.Laijang", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Saheibung", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Salbung Sehjang", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Salem Lhouthang", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Samuk", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Sinam Jonhol", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Sinam khaithong1", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Singda Kuki", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Songjang Waphong", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("T.Laijang", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Thangjing Chiru", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Thanglong Molbung", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Thingkhongjang", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Veitum Khullen", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("vengnom", "KANGCHUP GELJANG TD BLOCK");
     panchayatToBlockMap.put("Waphong Inthan", "KANGCHUP GELJANG TD BLOCK");

     // ===== KANGPOKPI =====
     panchayatToBlockMap.put("12 miles IT road", "KANGPOKPI");
     panchayatToBlockMap.put("Changoubung North", "KANGPOKPI");
     panchayatToBlockMap.put("Changoubung South", "KANGPOKPI");
     panchayatToBlockMap.put("Changoubung V.", "KANGPOKPI");
     panchayatToBlockMap.put("Chawangkining", "KANGPOKPI");
     panchayatToBlockMap.put("Chuchekhop(A) Irang Pt-II", "KANGPOKPI");
     panchayatToBlockMap.put("Chuchekhop(B)", "KANGPOKPI");
     panchayatToBlockMap.put("Chucheklop-(C)", "KANGPOKPI");
     panchayatToBlockMap.put("Dahalthari Irang Pt-1", "KANGPOKPI");
     panchayatToBlockMap.put("Daili", "KANGPOKPI");
     panchayatToBlockMap.put("Dulen", "KANGPOKPI");
     panchayatToBlockMap.put("Ghimethari", "KANGPOKPI");
     panchayatToBlockMap.put("Haijang", "KANGPOKPI");
     panchayatToBlockMap.put("Harup Maohing", "KANGPOKPI");
     panchayatToBlockMap.put("Hengbung", "KANGPOKPI");
     panchayatToBlockMap.put("Kailenjang", "KANGPOKPI");
     panchayatToBlockMap.put("Kalapahar", "KANGPOKPI");
     panchayatToBlockMap.put("Kalapahar(N)", "KANGPOKPI");
     panchayatToBlockMap.put("Kangpokpi Ward No.1", "KANGPOKPI");
     panchayatToBlockMap.put("Kangpokpi Ward No.10", "KANGPOKPI");
     panchayatToBlockMap.put("Kangpokpi Ward No.11", "KANGPOKPI");
     panchayatToBlockMap.put("Kangpokpi Ward No.12", "KANGPOKPI");
     panchayatToBlockMap.put("Kangpokpi Ward No.13", "KANGPOKPI");
     panchayatToBlockMap.put("Kangpokpi Ward No.14", "KANGPOKPI");
     panchayatToBlockMap.put("Kangpokpi Ward No.2", "KANGPOKPI");
     panchayatToBlockMap.put("Kangpokpi Ward No.3", "KANGPOKPI");
     panchayatToBlockMap.put("Kangpokpi Ward No.4", "KANGPOKPI");
     panchayatToBlockMap.put("Kangpokpi Ward No.5", "KANGPOKPI");
     panchayatToBlockMap.put("Kangpokpi Ward No.6", "KANGPOKPI");
     panchayatToBlockMap.put("Kangpokpi Ward No.7", "KANGPOKPI");
     panchayatToBlockMap.put("Kangpokpi Ward No.8", "KANGPOKPI");
     panchayatToBlockMap.put("Kangpokpi Ward No.9", "KANGPOKPI");
     panchayatToBlockMap.put("Kazanga", "KANGPOKPI");
     panchayatToBlockMap.put("Kongpao", "KANGPOKPI");
     panchayatToBlockMap.put("Laikot", "KANGPOKPI");
     panchayatToBlockMap.put("Lhangnom", "KANGPOKPI");
     panchayatToBlockMap.put("Liyai Kalapahar", "KANGPOKPI");
     panchayatToBlockMap.put("Lungphou", "KANGPOKPI");
     panchayatToBlockMap.put("M/Ningthoupham", "KANGPOKPI");
     panchayatToBlockMap.put("Mahika", "KANGPOKPI");
     panchayatToBlockMap.put("Manedara Irang pt-1", "KANGPOKPI");
     panchayatToBlockMap.put("Maohing Kuki", "KANGPOKPI");
     panchayatToBlockMap.put("Maramei Naga", "KANGPOKPI");
     panchayatToBlockMap.put("Mayangkhang", "KANGPOKPI");
     panchayatToBlockMap.put("Mayangkhang Khunou", "KANGPOKPI");
     panchayatToBlockMap.put("Phyapou", "KANGPOKPI");
     panchayatToBlockMap.put("Poudel Basti", "KANGPOKPI");
     panchayatToBlockMap.put("S.Khonomphai", "KANGPOKPI");
     panchayatToBlockMap.put("School Praganda", "KANGPOKPI");
     panchayatToBlockMap.put("SIMOL", "KANGPOKPI");
     panchayatToBlockMap.put("Songpekjang", "KANGPOKPI");
     panchayatToBlockMap.put("Songtun (J)", "KANGPOKPI");
     panchayatToBlockMap.put("T.Aviall", "KANGPOKPI");
     panchayatToBlockMap.put("Tagaramphung Yaikongpao", "KANGPOKPI");
     panchayatToBlockMap.put("Tahar Basti", "KANGPOKPI");
     panchayatToBlockMap.put("Tamuyon Khullen", "KANGPOKPI");
     panchayatToBlockMap.put("Taphou Kuki", "KANGPOKPI");
     panchayatToBlockMap.put("Thonglang Akutpa", "KANGPOKPI");
     panchayatToBlockMap.put("Thonglang Atongba", "KANGPOKPI");
     panchayatToBlockMap.put("Toribari", "KANGPOKPI");
     panchayatToBlockMap.put("Toribari(N)", "KANGPOKPI");
     panchayatToBlockMap.put("Tumnoupokpi", "KANGPOKPI");
     panchayatToBlockMap.put("West Haipi", "KANGPOKPI");

     // ===== LHUNGTIN TD BLOCK =====
     panchayatToBlockMap.put("B.Boljang", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("B.Khajang", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("C.Aisan", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("C.Kholen", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Chanmol", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Chingdai Khunou", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Chonjang", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Denglen", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Dongsum", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Gallam", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Gampum", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Gangpikon", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Gwaltabi", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("H. Yangom", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("H.Langjol", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("J.K.Lunglhaimun(Dongsum Machet)", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("K.Khonom", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("K.Laitul(Waichei)", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Khongbal Kuki", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("L Langjol (1)", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("L Phaijang (Phaijol)", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Laikot Kom", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Leplen", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Lhangsom", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Lhungtin", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Maojang", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Mojol", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Mokang Ngamneh", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Molcham", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Moljang", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Molkon", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Molkon Bazar", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Mongjang", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Mongneljang", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("N.Moulhoiphai", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("N.Phailen", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Naphai", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Natjang", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("New Seibol", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Ng.Phainom", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Nomjang", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("P.Phaimol", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Phaikon", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Puleijang", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("S.Khonomphai", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Samusong", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Semuol", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Sijang", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Somphung", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Songbem", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Songphel Khullen", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("T.Gamnom", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Tengkonphai", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Thingphai", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Tingpibung", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Twichin", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Twinomjang", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Twisomjang", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Urangpat", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Walpabung", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("Yangnoi", "LHUNGTIN TD BLOCK");
     panchayatToBlockMap.put("yagnongphai", "LHUNGTIN TD BLOCK"); // Note: corrected key if needed ("yagnongphai" vs "y an gnongphai")

     // ===== SAIKUL =====
     panchayatToBlockMap.put("A.Geljang", "SAIKUL");
     panchayatToBlockMap.put("A.Phainom", "SAIKUL");
     panchayatToBlockMap.put("A.Twisomjang", "SAIKUL");
     panchayatToBlockMap.put("Aigejang", "SAIKUL");
     panchayatToBlockMap.put("Ankhumbung", "SAIKUL");
     panchayatToBlockMap.put("Awanglonga Koireng", "SAIKUL");
     panchayatToBlockMap.put("Bilei", "SAIKUL");
     panchayatToBlockMap.put("Chalkot", "SAIKUL");
     panchayatToBlockMap.put("Challouphai", "SAIKUL");
     panchayatToBlockMap.put("Changsang", "SAIKUL");
     panchayatToBlockMap.put("Changsang Yangmol (Changsang Machet)", "SAIKUL");
     panchayatToBlockMap.put("Chingdai Khullen", "SAIKUL");
     panchayatToBlockMap.put("Chingka Lambi", "SAIKUL");
     panchayatToBlockMap.put("Chingmang", "SAIKUL");
     panchayatToBlockMap.put("Dimjang", "SAIKUL");
     panchayatToBlockMap.put("E.Mulam", "SAIKUL");
     panchayatToBlockMap.put("Ekouphai", "SAIKUL");
     panchayatToBlockMap.put("Ekpan Chingkha", "SAIKUL");
     panchayatToBlockMap.put("Gangpijang", "SAIKUL");
     panchayatToBlockMap.put("Govajang (Aigejang Machet)", "SAIKUL");
     panchayatToBlockMap.put("Gunphaibung", "SAIKUL");
     panchayatToBlockMap.put("Gunphaijang", "SAIKUL");
     panchayatToBlockMap.put("H Mollen", "SAIKUL");
     panchayatToBlockMap.put("H.Champhai", "SAIKUL");
     panchayatToBlockMap.put("H.Gelmol", "SAIKUL");
     panchayatToBlockMap.put("H.Khopibung", "SAIKUL");
     panchayatToBlockMap.put("H.Moulhoi", "SAIKUL");
     panchayatToBlockMap.put("Haibung", "SAIKUL");
     panchayatToBlockMap.put("Haokip Veng", "SAIKUL");
     panchayatToBlockMap.put("Happy Valley", "SAIKUL");
     panchayatToBlockMap.put("Holbung", "SAIKUL");
     panchayatToBlockMap.put("Ichaigojang", "SAIKUL");
     panchayatToBlockMap.put("Ichailamlan", "SAIKUL");
     panchayatToBlockMap.put("Khajang", "SAIKUL");
     panchayatToBlockMap.put("Khamenlok", "SAIKUL");
     panchayatToBlockMap.put("Khaochangbung", "SAIKUL");
     panchayatToBlockMap.put("Khokon", "SAIKUL");
     panchayatToBlockMap.put("Khongbal Tangkhul", "SAIKUL");
     panchayatToBlockMap.put("Khongnangpokpi", "SAIKUL");
     panchayatToBlockMap.put("L.Chajang", "SAIKUL");
     panchayatToBlockMap.put("L.Lajang", "SAIKUL");
     panchayatToBlockMap.put("L.Lhangjol", "SAIKUL");
     panchayatToBlockMap.put("Lairok Kom", "SAIKUL");
     panchayatToBlockMap.put("Leikot", "SAIKUL");
     panchayatToBlockMap.put("Lhungjang", "SAIKUL");
     panchayatToBlockMap.put("Luwangsangol(Ekpan Khullen)", "SAIKUL");
     panchayatToBlockMap.put("M.Bunglung", "SAIKUL");
     panchayatToBlockMap.put("M.Kholmun", "SAIKUL");
     panchayatToBlockMap.put("Maibung Kom", "SAIKUL");
     panchayatToBlockMap.put("Maibung Likli", "SAIKUL");
     panchayatToBlockMap.put("Makokching", "SAIKUL");
     panchayatToBlockMap.put("Makokching B", "SAIKUL");
     panchayatToBlockMap.put("Mapao Christian (T)", "SAIKUL");
     panchayatToBlockMap.put("Mapao Khullen (T)", "SAIKUL");
     panchayatToBlockMap.put("Mapao Thangal", "SAIKUL");
     panchayatToBlockMap.put("Molkot", "SAIKUL");
     panchayatToBlockMap.put("Molvom Villge", "SAIKUL");
     panchayatToBlockMap.put("Moulhoi", "SAIKUL");
     panchayatToBlockMap.put("N.Chaljang", "SAIKUL");
     panchayatToBlockMap.put("N.Zilphai", "SAIKUL");
     panchayatToBlockMap.put("New Boljang", "SAIKUL");
     panchayatToBlockMap.put("New Saikul", "SAIKUL");
     panchayatToBlockMap.put("Ngakhapat", "SAIKUL");
     panchayatToBlockMap.put("Ngarongchingjen", "SAIKUL");
     panchayatToBlockMap.put("Nungka", "SAIKUL");
     panchayatToBlockMap.put("Nuranthel Boljang", "SAIKUL");
     panchayatToBlockMap.put("Nurathel", "SAIKUL");
     panchayatToBlockMap.put("Old Boljang", "SAIKUL");
     panchayatToBlockMap.put("P Geljang Villge", "SAIKUL");
     panchayatToBlockMap.put("P.Khonomphai", "SAIKUL");
     panchayatToBlockMap.put("Pangjang", "SAIKUL");
     panchayatToBlockMap.put("Phaijang", "SAIKUL");
     panchayatToBlockMap.put("Phaileng", "SAIKUL");
     panchayatToBlockMap.put("Phainom (1)", "SAIKUL");
     panchayatToBlockMap.put("Philen", "SAIKUL");
     panchayatToBlockMap.put("Purum Khullen", "SAIKUL");
     panchayatToBlockMap.put("Purum Likli", "SAIKUL");
     panchayatToBlockMap.put("S. Boijang", "SAIKUL");
     panchayatToBlockMap.put("S.Bolkot", "SAIKUL");
     panchayatToBlockMap.put("S.Mongbung", "SAIKUL");
     panchayatToBlockMap.put("S.Phaileng Kot", "SAIKUL");
     panchayatToBlockMap.put("Sadu Koireng", "SAIKUL");
     panchayatToBlockMap.put("Saijang", "SAIKUL");
     panchayatToBlockMap.put("Saikul", "SAIKUL");
     panchayatToBlockMap.put("Saikul Hill Town", "SAIKUL");
     panchayatToBlockMap.put("Satang Kuki", "SAIKUL");
     panchayatToBlockMap.put("Sinam Kom", "SAIKUL");
     panchayatToBlockMap.put("Songjang", "SAIKUL");
     panchayatToBlockMap.put("Songpehjang", "SAIKUL");
     panchayatToBlockMap.put("Songphel L", "SAIKUL");
     panchayatToBlockMap.put("Songthu Avenue", "SAIKUL");
     panchayatToBlockMap.put("T Wakanphai", "SAIKUL");
     panchayatToBlockMap.put("T.Gojang", "SAIKUL");
     panchayatToBlockMap.put("T.Jordenphai (Thombol Machet)", "SAIKUL");
     panchayatToBlockMap.put("T.Lamkajang", "SAIKUL");
     panchayatToBlockMap.put("T.Thangkan", "SAIKUL");
     panchayatToBlockMap.put("Tamaching Tkl", "SAIKUL");
     panchayatToBlockMap.put("Taothang Veng", "SAIKUL");
     panchayatToBlockMap.put("Thangal Sarung", "SAIKUL");
     panchayatToBlockMap.put("Thangkanphai", "SAIKUL");
     panchayatToBlockMap.put("Thingjang", "SAIKUL");
     panchayatToBlockMap.put("Thingsat", "SAIKUL");
     panchayatToBlockMap.put("Thombol", "SAIKUL");
     panchayatToBlockMap.put("Thongnangpal", "SAIKUL");
     panchayatToBlockMap.put("Tusam", "SAIKUL");
     panchayatToBlockMap.put("Twichamphai", "SAIKUL");
     panchayatToBlockMap.put("Utonglok", "SAIKUL");
     panchayatToBlockMap.put("Wakan", "SAIKUL");
     panchayatToBlockMap.put("Y. Langkhong", "SAIKUL");

     // ===== SAITU GAMPHAZOL =====
     panchayatToBlockMap.put("A.Songpijang", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Bethany", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Bethsaida", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Bolkot", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Bongjol", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("C. Phaillen", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("C.Joujang", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("C.Munnom", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Ch.Ollim", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Chalbol", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Chalbung", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Dwarika Nepali", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("E.Sapormeina", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("G.Bunglen", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("G.Gelbung", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("G.Hengjang", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("G.Lhangjol", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("G.Lhangsom", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("G.Phalbung", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("G.Saparmeina", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("G.Songlung", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("G.Thangbuh", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Gamgiphai", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Goungaiphai", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Haijol", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Haiken", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Hermon", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("HN Champhai", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("J.KHONUMJANG", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("J.Tuiphai", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Joujang", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Joulen", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("K. Phoipi", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("K.Lhangnom", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("K.Mollen", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("K.Orphanage", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Kangchup Joute", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Kanglatongbi Mollen", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Khengjang", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Khochal", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Khokheng", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Kholenphai", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("KHOLEP", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Khongkhaijang", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Khonomjang", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Khunkhu Kuki", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Khunkhu Naga", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Kolpechang Kuki", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Koubroleika(N)", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Koubruleikha", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("L. MANGJOL", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("L.Gamngai (Munpi)", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("L.Gunphai", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("L.Khomunnom", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("L.Simol", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Leikot", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Lhangkichoi", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("LOWER KHENGJANG", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("M.Jangnomphai", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("M.Songpi", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Makhan", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Moljol", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Molnoi", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Mongjang", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Mongpijang", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Mongtung", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Motbung", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Motjang", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Moulthang", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("N.Champhai", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("N.Khonom", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("N.N.KHONOMPHAI", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("N.Songlung", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("NEW SELSI", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("O.S.Tuinom", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("P.Champhai", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("PANGMOL", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Pangsang", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Phaijang", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Phaijol", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Phailengkot", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Phoibi", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Phoilen", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("S.Bollen", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("S.Boungpi", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("S.Buning", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("S.Chajang", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("S.Gamnomjang", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("S.Khajang", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("S.Lhangnom", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("S.Molcham", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("S.Silen", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("S.SIMTOL", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("S.Vengnom", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Saitu", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Saitu-Saparmeina", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Santing", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Saparmeina", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("sekmai leikhampokpi", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Seloi", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Selsi", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Sipijang", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Songjang Khullen", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("T.Chaljang", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("T.Kiplou", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("T.Simol", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Taloulong", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Taniulong Langka", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Thingbongjang", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Thomjang", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("TL.Jalenmol", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Tuipajang", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("U.Saparmeina (Salem) village", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("W.Buning", "SAITU GAMPHAZOL");
     panchayatToBlockMap.put("Zalenbung", "SAITU GAMPHAZOL");

     // ===== T. VAICHONG TD BLOCK =====
     panchayatToBlockMap.put("Bajagra", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("Beleijang", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("Bollen", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("Chalwa", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("Dhorigari", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("Gelbung", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("Geljang", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("Gelnal", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("Gorkha Harup", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("Gorkha Jhil", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("Gorkha Tapon", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("Govajang", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("Grouping Centre Songbhuphai", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("Haimol", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("Harup Khopi", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("Harup Naga 1", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("Haspukhri", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("Holjang", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("Khakare", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("Kharpani", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("Khomunnom", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("Kolgari", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("Kotlen", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("L. Sehjang", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("Lamchok Irang Pt-1", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("Leisang", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("Lhangjang", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("M. Wakotphai (Makui Mayankham)", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("M.Chaljang", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("Makui Ashang", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("Makui Naga", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("Maokot", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("N.Teikhang", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("Naibet", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("Panikheti", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("Phoikon", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("Rijalthar", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("S. phailen", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("Sangjang Pakang", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("Selsi", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("Songpijang", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("T.Khonomphai", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("Tapon Naga", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("Thaldara", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("Thebram", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("Thulochor", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("Timsina", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("Tuijang Vaichong", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("V Kholen", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("W Joupi", "T. VAICHONG TD BLOCK");
     panchayatToBlockMap.put("West Santing", "T. VAICHONG TD BLOCK");

 }


 public static String getBlock(String panchayat) {
     if (panchayat == null) return null;
     String exact = panchayatToBlockMap.get(panchayat);
     if (exact != null) return exact;
     return panchayatToBlockMap.get(panchayat.trim());
 }

}

